---
- name: setup docker
  hosts: homeservers
  remote_user: ansible

  tasks:
    - name: remove any existing docker installations
      become: true
      ansible.builtin.command:
        cmd: >
          dnf remove docker 
          docker-client 
          docker-client-latest 
          docker-common 
          docker-latest 
          docker-latest-logrotate 
          docker-selinux
          docker-engine-selinux
          docker-engine
